package GUI;

/**
 *
 * @author 293876
 *
 */
import Classes.Estoque;
import Classes.Item;
import Classes.Itens;
import DAO.ErpDAOException;
import DAO.ItensDAO;
import DAO.EstoqueDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AdicionarItem extends javax.swing.JFrame {

    ArrayList<Estoque> estoque = new ArrayList();
    ItensDAO IDAO = new ItensDAO();
    int ID_emprestimo;

    public AdicionarItem(int codigo) {
        initComponents();
        ID_emprestimo = codigo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABELA = new javax.swing.JTable();
        ADICIONAR = new javax.swing.JButton();
        SAIR = new javax.swing.JButton();
        QUANTIDADE = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Adicionar item");

        TABELA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Item", "Descrição", "Quantidade", "Emprestados", "Disponivel?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TABELA.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TABELA);
        if (TABELA.getColumnModel().getColumnCount() > 0) {
            TABELA.getColumnModel().getColumn(0).setMinWidth(0);
            TABELA.getColumnModel().getColumn(0).setPreferredWidth(0);
            TABELA.getColumnModel().getColumn(0).setMaxWidth(0);
            TABELA.getColumnModel().getColumn(1).setMinWidth(120);
            TABELA.getColumnModel().getColumn(2).setMinWidth(120);
            TABELA.getColumnModel().getColumn(3).setMinWidth(30);
            TABELA.getColumnModel().getColumn(3).setPreferredWidth(80);
            TABELA.getColumnModel().getColumn(3).setMaxWidth(100);
            TABELA.getColumnModel().getColumn(4).setMinWidth(30);
            TABELA.getColumnModel().getColumn(4).setPreferredWidth(80);
            TABELA.getColumnModel().getColumn(4).setMaxWidth(100);
            TABELA.getColumnModel().getColumn(5).setMinWidth(30);
            TABELA.getColumnModel().getColumn(5).setPreferredWidth(80);
            TABELA.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        ADICIONAR.setText("Adicionar");
        ADICIONAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADICIONARActionPerformed(evt);
            }
        });

        SAIR.setText("Sair");
        SAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIRActionPerformed(evt);
            }
        });

        jLabel12.setText("Quantidade a ser adicionada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ADICIONAR)
                        .addGap(43, 43, 43)
                        .addComponent(SAIR)
                        .addGap(456, 456, 456))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(QUANTIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(484, 484, 484))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(465, 465, 465)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QUANTIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADICIONAR)
                    .addComponent(SAIR))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        carrega_tabela();
    }//GEN-LAST:event_formWindowOpened

    private void SAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIRActionPerformed
        dispose();
    }//GEN-LAST:event_SAIRActionPerformed

    private void ADICIONARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADICIONARActionPerformed
        Itens ite = new Itens();
        EstoqueDAO EDAO = new EstoqueDAO();
        int linha_selecionada, id_item, subtracao = 0;
        ite.setID_emprestimo(ID_emprestimo);
        linha_selecionada = TABELA.getSelectedRow();
        
        // Validação: Verifica se uma linha foi selecionada
        if (linha_selecionada < 0) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um item na tabela.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validação: Verifica se a quantidade foi preenchida
        if (QUANTIDADE.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha a quantidade de itens a ser adicionada.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int qtd;
        try {
            qtd = Integer.parseInt(QUANTIDADE.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "A quantidade deve ser um número inteiro válido.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (qtd <= 0) {
            JOptionPane.showMessageDialog(this, "A quantidade não pode ser negativa ou zero.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
        } else {
            // Validação: Verifica se o item está disponível (Sim/Não na tabela)
            String disponivelTexto = (String) TABELA.getModel().getValueAt(linha_selecionada, 5);
            
            // Validação:Verifica a quantidade física no estoque
            int qtdEstoque = Integer.parseInt((String) TABELA.getModel().getValueAt(linha_selecionada, 3));

            if (disponivelTexto.equals("Não")) {
                JOptionPane.showMessageDialog(this, "Este item está marcado como INDISPONÍVEL ou INATIVO e não pode ser emprestado.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (qtdEstoque <= 0) {
                JOptionPane.showMessageDialog(this, "Não há unidades deste item disponíveis no estoque físico.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (qtd > qtdEstoque) {
                JOptionPane.showMessageDialog(this, "A quantidade solicitada (" + qtd + ") é maior que a quantidade disponível em estoque (" + qtdEstoque + ").", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
            } else {
                id_item = Integer.parseInt((String) TABELA.getModel().getValueAt(linha_selecionada, 0));
                ite.setID_item(id_item);
                ite.setQtd(qtd);

                subtracao = qtdEstoque - qtd;

                try {
                    IDAO.InserirItem(ite);
                    JOptionPane.showMessageDialog(this, "Item adicionado com sucesso! Atualize a tabela na tela 'Novo empréstimo'.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    carrega_tabela();
                    EDAO.AtualizarQuantidade(id_item, subtracao);
                    QUANTIDADE.setText("");
                } catch (ErpDAOException ex) {
                    System.out.println("falha ao inserir");
                    JOptionPane.showMessageDialog(this, "Erro ao adicionar item. Tente novamente.", "Erro", JOptionPane.ERROR_MESSAGE);
                }
                dispose();
            }
        }

    }//GEN-LAST:event_ADICIONARActionPerformed

    /**
     * @param args the command line arguments
     */
    public void carrega_tabela() {
        DefaultTableModel table = (DefaultTableModel) TABELA.getModel();
        String item, descricao, status = null;
        int ID_item, quantidade, emprestados, indisponivel, inativo;

        if (TABELA.getRowCount() > 0) {
            while (TABELA.getRowCount() > 0) {
                table.removeRow(0);
            }
        }

        try {
            EstoqueDAO ESDAO = new EstoqueDAO();
            estoque = ESDAO.Listar();
        } catch (Exception ex) {
            System.out.println("Erro de conexão ao banco.");
        }

        for (int i = 0; i < estoque.size(); i++) {
            ID_item = estoque.get(i).getID_item();
            item = estoque.get(i).getItem();
            descricao = estoque.get(i).getDescricao();
            quantidade = estoque.get(i).getQuantidade();
            emprestados = estoque.get(i).getEmprestados();
            indisponivel = estoque.get(i).getIndisponivel();
            inativo = estoque.get(i).getInativo();
            
            // Regra de negócio: Item é disponível apenas se não estiver indisponível E não estiver inativo
            if (indisponivel == 0 && inativo == 0) {
                status = "Sim";
            } else {
                status = "Não";
            }
            table.addRow(new String[]{String.valueOf(ID_item), item, descricao, String.valueOf(quantidade), String.valueOf(emprestados), status});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADICIONAR;
    private javax.swing.JTextField QUANTIDADE;
    private javax.swing.JButton SAIR;
    private javax.swing.JTable TABELA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
