/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.Estoque;
import Classes.Item;
import DAO.EstoqueDAO;
import DAO.ItensDAO;

/**
 *
 * @author 294055
 */
public class CadastroItem extends javax.swing.JFrame {

    /**
     * Creates new form cadastroItem
     */
    public CadastroItem() {
        // 1. CHAMA initComponents()
    initComponents(); 

    // 2. AGORA, OS BOTÕES btnsalvar e btnfechar FORAM CRIADOS.
    // ONDE ESTÁ O ERRO
    // btnsalvar.setMnemonic('o'); 
    // btnfechar.setMnemonic('c');
    
    // 3. Define a localização e, em seguida, define as propriedades DOS BOTÕES JÁ CRIADOS.
    setLocationRelativeTo(null);
    
    // CORREÇÃO: Mantenha as definições do botão AQUI, após a inicialização.
    btnsalvar.setMnemonic('o');
    btnfechar.setMnemonic('c');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextItem = new javax.swing.JTextField();
        TextQuantidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        qtn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextDescricao = new javax.swing.JTextField();
        btnsalvar = new javax.swing.JToggleButton();
        btnfechar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextQuantidadeActionPerformed(evt);
            }
        });

        jLabel1.setText("item");

        qtn.setText("quantidae");

        jLabel3.setText("descricao");

        btnsalvar.setText("salvar");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        btnfechar.setText("fechar");
        btnfechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(qtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextItem)
                    .addComponent(TextDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(TextQuantidade))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnfechar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnsalvar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsalvar)
                    .addComponent(btnfechar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextQuantidadeActionPerformed

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        try {
            String Item = TextItem.getText();
            int Quantidade = Integer.parseInt(TextQuantidade.getText());
            String Descricao = TextDescricao.getText();
            int emprestado = 0;
            int indisponivel = 0;
            int inativo = 0;
            Estoque item = new Estoque(0, Item, Quantidade, Descricao, emprestado, indisponivel, inativo);

            EstoqueDAO dao = new EstoqueDAO();

            dao.inserir(item);

            javax.swing.JOptionPane.showMessageDialog(this, "item inserido com sucesso!");
            dispose();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao inserir item: " + e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btnfecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnfecharActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextDescricao;
    private javax.swing.JTextField TextItem;
    private javax.swing.JTextField TextQuantidade;
    private javax.swing.JToggleButton btnfechar;
    private javax.swing.JToggleButton btnsalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel qtn;
    // End of variables declaration//GEN-END:variables
}
