/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.Usuario;
import DAO.ErpDAOException;
import DAO.UsuarioDAO;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 294067
 */
public class GerenciamentoDeUsuarios extends javax.swing.JFrame {

    ArrayList<Usuario> usuarios = new ArrayList();
    
    public GerenciamentoDeUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        Exit = new javax.swing.JButton();
        Troca = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "Nome", "Login", "Administrador", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TabelaMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);
        if (Tabela.getColumnModel().getColumnCount() > 0) {
            Tabela.getColumnModel().getColumn(0).setMinWidth(0);
            Tabela.getColumnModel().getColumn(0).setPreferredWidth(0);
            Tabela.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        Exit.setText("Voltar");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Troca.setText("Trocar senha");
        Troca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrocaActionPerformed(evt);
            }
        });

        add.setText("Adicionar usuario");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jLabel1.setText("Dê duplo clique sobre o usuário para alterar seus dados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Exit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Troca)
                        .addGap(56, 56, 56)
                        .addComponent(add)
                        .addGap(19, 19, 19))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Exit)
                    .addComponent(Troca)
                    .addComponent(add))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        carrega();
    }//GEN-LAST:event_formComponentShown

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        if (evt.getClickCount() == 2) {
        
        int linha, id;

        linha = Tabela.getSelectedRow();

        if (linha != -1) {
            
            try {
                Object idObjeto = Tabela.getModel().getValueAt(linha, 0); 
                
                if (idObjeto instanceof Integer integer) {
                    id = integer;
                } else {
                    id = Integer.parseInt(idObjeto.toString()); 
                }

                JFrame novo = new AlterarUsuario(id);
                novo.setLocationRelativeTo(rootPane);
                novo.setVisible(true);
                dispose();

            } catch (NumberFormatException e) {
                System.err.println("Erro de formato de número na JTable: " + e.getMessage());
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "O ID da linha selecionada não é um número válido.", 
                    "Erro de Dados", javax.swing.JOptionPane.ERROR_MESSAGE);
            } catch (ErpDAOException ex) {
                Logger.getLogger(GerenciamentoDeUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }     
    }//GEN-LAST:event_TabelaMouseClicked

    private void TabelaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_TabelaMouseEntered

    private void TrocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrocaActionPerformed
        int linha, id;

        linha = Tabela.getSelectedRow();

        if (linha != -1) {
            
            try {
                Object idObjeto = Tabela.getModel().getValueAt(linha, 0); 
                
                if (idObjeto instanceof Integer integer) {
                    id = integer;
                } else {
                    id = Integer.parseInt(idObjeto.toString()); 
                }

                JFrame novo = new TrocaSenha(id);
                novo.setLocationRelativeTo(rootPane);
                novo.setVisible(true);
                dispose();

            } catch (NumberFormatException e) {

                System.err.println("Erro de formato de número na JTable: " + e.getMessage());
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "O ID da linha selecionada não é um número válido.", 
                    "Erro de Dados", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_TrocaActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
                JFrame novo = new AdicionarUsuario();
                novo.setLocationRelativeTo(rootPane);
                novo.setVisible(true);
                dispose();
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JTable Tabela;
    private javax.swing.JButton Troca;
    private javax.swing.JButton add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
     public void carrega() {

        DefaultTableModel table = (DefaultTableModel) Tabela.getModel();
        String nome,login,adm,inat;
        int id,admin,inativo;
        DateFormat dtOutput = new SimpleDateFormat("dd/MM/yyyy");

        if (Tabela.getRowCount() > 0) {
            while (Tabela.getRowCount() > 0) {
                table.removeRow(0);
            }
        }

        UsuarioDAO CDAO;

        try {
            CDAO = new UsuarioDAO();
            usuarios = CDAO.Listar();
        } catch (Exception ex) {
            System.out.println("Erro de conexão ao banco.");
        }

        for (int i = 0; i < usuarios.size(); i++) {
            id = usuarios.get(i).getID_usuario();
            nome = usuarios.get(i).getNome();
            login = usuarios.get(i).getLogin();
            admin = usuarios.get(i).getAdministrador();
            inativo = usuarios.get(i).getInativo();
            if(admin == 0){
                adm = "Nao";
            } else{
                adm = "Sim";
            }
            if(inativo == 0){
                inat = "Ativo";
            }else{
                inat = "Inativo";
            }
            table.addRow(new String[]{String.valueOf(id),nome,login,adm,inat});
        }
    }
}
